name: Deploy to server LightSail TurnoFarm

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          key_type: pem
          port: 22
          #levantar frontend
          script: |
            cd /home/bitnami/htdocs/farmachile-web
            git clean -f
            git pull origin main
            npm install 
            npm run build
            sudo cp -r /home/bitnami/htdocs/farmachile-web/build/* /opt/bitnami/apache/htdocs/
            
            
