name: Deploy to server LightSail

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          key_type: pem
          port: 22
          script: |
            cd /home/bitnami/htdocs/backend-graphql-impch
            git clean -f
            git pull origin main
            npm install --only=prod
            pm2 delete graphql-impch
            pm2 list
            pm2 start npm --name "graphql-impch" -- start